services:
  rabbitmq1:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "P@ssw0rd123"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /var/log/rabbitmq1:/var/log/rabbitmq
  
  rabbitmq2:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "P@ssw0rd123"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - /var/log/rabbitmq2:/var/log/rabbitmq
    depends_on:
      - rabbitmq1