services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: ${CONTAINER_NAME}
    environment:
      - cluster.name=${CLUSTER_NAME}
      - xpack.security.enabled=false
      - discovery.type=single-node
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - "./elasticsearch-data:/usr/share/elasticsearch/data"
    ports:
      - ${ES_PORT}:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_HOST}
    ports:
      - ${KIBANA_PORT}:5601
    mem_limit: ${KB_MEM_LIMIT}
    depends_on:
      - elasticsearch

  logstash:
   image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
   labels:
     co.elastic.logs/module: logstash
   user: root
   volumes:
     - "./logstashdata:/usr/share/logstash/data"
     - "./logstash_ingest_data:/usr/share/logstash/ingest_data/"
     - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
     - "./nginx/log:/usr/share/logstash/nginx/log:ro"
   environment:
     - xpack.monitoring.enabled=false
     - ELASTIC_HOSTS=${ELASTIC_HOST}
   mem_limit: ${LS_MEM_LIMIT}
   depends_on:
     - elasticsearch
     - nginx

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:${STACK_VERSION}
  #   command: --strict.perms=false
  #   user: root
  #   volumes:
  #     - /projects/test/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - /var/lib/docker:/var/lib/docker:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  
  nginx:
    image: docker.io/bitnami/nginx:${NGINX_VERSION}
    ports:
      - '${NGINX_PORT}:80'
    volumes: 
    - "./nginx/log/access.log:/var/log/nginx/access.log"
    - "./nginx/log/error.log:/var/log/nginx/error.log"

volumes:
  elasticsearch-data:
  logstashdata:
  