services:
  db_s1:
    image: postgres:18
    restart: always
    container_name: db_s1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: my_db
    ports:
      - 5432:5432
    volumes:
      - ./shard1.sql:./docker-entrypoint-initdb.d/shard.sql

  db_s2:
    image: postgres:18
    restart: always
    container_name: db_s2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: my_db
    ports:
      - 5433:5432
    volumes:
      - ./shard2.sql:./docker-entrypoint-initdb.d/shard.sql

  db_s3:
    image: postgres:18
    restart: always
    container_name: db_s3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: my_db
    ports:
      - 5434:5432
    volumes:
      - ./shard3.sql:./docker-entrypoint-initdb.d/shard.sql
    